version: "3.9"

networks:
  bblc_customer:
    name: bblc_customer_net

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api_dev
    container_name: backend
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "16692:16692"
    volumes:
      - ./api:/var/www/html
      - /var/www/html/vendor
    networks:
      - bblc_customer

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: app_dev
    container_name: frontend
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - api
    ports:
      - 16694:16694
    volumes:
      - ./app:/var/www/html
      - /var/www/html/node_modules
    environment:
      - WDS_SOCKET_PORT=16694
      - CHOKIDAR_USEPOLLING=true
    networks:
      - bblc_customer

  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   tty: true
  #   ports:
  #     - 1433:1433
  #   volumes:
  #     - ./:/var/lib/mssqlql/data
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=p@ssw0rd
  #   networks:
  #     - bblc
