version: "3.9"

volumes:
  app_build:
    external: true

networks:
  bblc_customer:
    name: bblc_customer_net

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api_prod
    container_name: backend
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 16692:16692
      - 80:80
      - 443:443
    volumes:
      - ./api:/var/www/html
      - /api/vendor
      - app_build:/var/www/html/portal
    networks:
      - bblc_customer

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: app_prod
      args:
        build_dir: portal
    container_name: frontend
    restart: on-failure:3
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./app:/var/www/html
      - /app/node_modules
      - app_build:/var/www/html/portal
    networks:
      - bblc_customer

  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   tty: true
  #   ports:
  #     - 1433:1433
  #   volumes:
  #     - ./:/var/lib/mssqlql/data
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=p@ssw0rd
  #   networks:
  #     - bblc
